resources:
  - ../base/
nameSuffix: -production
patchesStrategicMerge:
  - set_static_ip.yaml
  - attach_backend_config.yaml
  - attach_frontend_config.yaml
  - attach_service_to_ingress.yaml
  - deployment.yaml
  - prod_cert.yaml