apiVersion: v1
kind: Service
metadata:
  name: freenet-org
  namespace: freenetorg
  annotations:
    cloud.google.com/backend-config: '{"default" : "backend-config-staging"}'
spec:
  selector:
    app: freenet-org-staging