apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-https-ingress
  namespace: freenetorg
spec:
  defaultBackend:
    service:
      name: freenet-org-staging
      port:
        number:
          8080
